### PR TITLE
fix: remove .directory from the repo. created by dolphin file manager

### PR DESCRIPTION
**Pull request by salmanishere**

### CODE REVIEW

**Comment by ebrahimraeyat** [comment]
Thanks. done in https://github.com/ebrahimraeyat/civilTools/commit/d188ede4d7cbd36685b81eb4ab6d63c19e502597

**Comment by salmanishere** [comment]
You forgot to delete .directory from the repo.

As a friendly advice, you can also press *merge* to merge the branches automatically instead of doing it manually, which is error-prone.

**Comment by ebrahimraeyat** [comment]
I don't understand why when i add .directory to .gitignor, git still add this kind of this file to repository. but for other file it is correct. I mean it must automatically remove .directory from my git!
because .directory not only in main directory and is on all my directory.
i found the error and fixed that:
[fix .gitignore](https://digitizor.com/gitignore-not-ignoring-files-how-to-fix/)

https://github.com/ebrahimraeyat/civilTools/commit/fc7e0c4beef94b303225e4beda8c0625ef025095

thank you so much.

**Comment by salmanishere** [comment]
It's not a bug, it's a feature. `.gitignore` does not affect the files that you _already_ have committed and exist in the repository. 

[https://git-scm.com/docs/gitignore](https://git-scm.com/docs/gitignore) says:

> The purpose of gitignore files is to ensure that certain files not tracked by Git remain untracked.
> To stop tracking a file that is currently tracked, use git rm --cached.

**Comment by ebrahimraeyat** [comment]
Thanks.

**Pull request closed without merging**
